import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Sidebar from "@/components/Sidebar";
import RecentesEvents from "@/components/layout/RecentesEvents";
import Gradiente from "@/components/Gradiente";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Evetily",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background relative h-screen isolate`}>
        <div className="grid grid-cols-12">
          <div className="hidden md:block col-span-2 relative">
            <Sidebar />
          </div>
          <div className="w-full col-span-10">
            <NavBar />
            <main className='text-white px-4 grid grid-cols-12 gap-2 relative z-10'>
              <div className='col-span-12'>
                {children}
              </div>
              {/* <div className='col-span-3'>
                <RecentesEvents />
              </div> */}
            </main>
          </div>
        </div>
        <Gradiente />
      </body>
    </html>
  );
}
