import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Sidebar from "@/components/Sidebar";
import RecentesEvents from "@/components/layout/RecentesEvents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Evetily",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#141414] h-screen flex justify-center`}>
        <div className="flex flex-wrap w-full max-w-screen-2xl">
          <div className="hidden md:block md:w-[13.666667%] bg-gray-200 relative">
            <Sidebar />
          </div>
          <div className="w-full md:w-2/3">
            <NavBar />
            <main className='text-white px-2 pt-[100px]'>
              {children}
            </main>
          </div>
          <div className="hidden md:block md:w-[19.666667%] relative">
            <RecentesEvents />
          </div>
        </div>
      </body>
    </html>
  );
}
